-- MySQL Script generated by MySQL Workbench
-- 06/26/15 19:23:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Faculties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Faculties` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Faculties` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `FacultyName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `StudentName` VARCHAR(45) NULL COMMENT '',
  `StudentNumber` VARCHAR(45) NULL COMMENT '',
  `Faculties_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Faculties_id`)  COMMENT '',
  INDEX `fk_Students_Faculties1_idx` (`Faculties_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Students_Faculties1`
    FOREIGN KEY (`Faculties_id`)
    REFERENCES `mydb`.`Faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professors` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ProfessorName` VARCHAR(45) NULL COMMENT '',
  `Title` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `CourseName` VARCHAR(45) NULL COMMENT '',
  `Professors_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Professors_id`)  COMMENT '',
  INDEX `fk_Courses_Professors1_idx` (`Professors_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Courses_Professors1`
    FOREIGN KEY (`Professors_id`)
    REFERENCES `mydb`.`Professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departments` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `DepartmentName` VARCHAR(45) NOT NULL COMMENT '',
  `Professors_id` INT NOT NULL COMMENT '',
  `Faculties_id` INT NOT NULL COMMENT '',
  `Courses_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Professors_id`, `Faculties_id`, `Courses_id`)  COMMENT '',
  INDEX `fk_Departments_Professors1_idx` (`Professors_id` ASC)  COMMENT '',
  INDEX `fk_Departments_Faculties1_idx` (`Faculties_id` ASC)  COMMENT '',
  INDEX `fk_Departments_Courses1_idx` (`Courses_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Departments_Professors1`
    FOREIGN KEY (`Professors_id`)
    REFERENCES `mydb`.`Professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departments_Faculties1`
    FOREIGN KEY (`Faculties_id`)
    REFERENCES `mydb`.`Faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departments_Courses1`
    FOREIGN KEY (`Courses_id`)
    REFERENCES `mydb`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students_has_Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students_has_Courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students_has_Courses` (
  `Students_id` INT NOT NULL COMMENT '',
  `Courses_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Students_id`, `Courses_id`)  COMMENT '',
  INDEX `fk_Students_has_Courses_Courses1_idx` (`Courses_id` ASC)  COMMENT '',
  INDEX `fk_Students_has_Courses_Students1_idx` (`Students_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Students_has_Courses_Students1`
    FOREIGN KEY (`Students_id`)
    REFERENCES `mydb`.`Students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_has_Courses_Courses1`
    FOREIGN KEY (`Courses_id`)
    REFERENCES `mydb`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
